---
title: Zheng Yang's Blog
SEOTitle: 杨正浩的博客
header-img: img/post-bg-index.jpg
email: 1358709431@qq.com
description: 做一个有灵魂的程序员
keyword: 杨正浩的博客, Zheng Yang, 杨正浩, Java,后端开发
url: https://nchu-student-6.github.io/
baseurl: ""
github_repo: https://github.com/nchu-student-6/nchu-student-6.github.io
sidebar: true
sidebar-about-description: 雄关漫道真如铁 而今迈步从头越。
sidebar-avatar: /img/ZhengYang.jpg
RSS: false
weibo_username: wzb1994
zhihu_username: 38-64-26-80
nowcoder_username: 243125981
github_username: nchu-student-6
leetcode_username: vibrant-euclidbvb
twitter_username: wzbcode
nowcoder_username: student6
permalink: pretty
paginate: 10
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
anchorjs: true
gems:
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
disqus_shortname: disqus_dfI4XpjFuM
gitalk:
  enable: false
  clientID: ae47d898c3d118b467be
  clientSecret: c30e8df95d413ec73785dea5b4237424165f77c7
  repo: flyingwzb.github.io
  owner: flyingwzb
  admin: flyingwzb
  distractionFreeMode: true
featured-tags: true
featured-condition-size: 0
chrome-tab-theme-color: "#000000"
service-worker: true
friends:
  - title: 书舟网
    href: http://kindle.archiew.top/
  - title: 阮一峰
    href: http://www.ruanyifeng.com/home.html
  - title: 阿里巴巴
    href: https://www.alibabagroup.com/cn/global/home
  - title: 腾讯
    href: https://www.tencent.com/zh-cn/index.html
  - title: 字节跳动
    href: https://www.bytedance.com/zh
  - title: 语雀
    href: https://www.yuque.com/dashboard/books
